### ISSUE TITLE
For 'get in touch' section

### ISSUE THREAD

**Issue by RuchiGitHu** [CSwala/CSwala-website#16]
The section 'get in touch' have same color as footer as a result the footer looks too long as compare to website. I think the color should be different from footer, so that the 'get in touch' should not look like a part of footer, also the creativity will make it more visible. if we proceed this changes then footer will also look different like landing section and about section. 
Looking forward to contribute here.
Please assign this issue to me under gssoc21.

**Comment by riturajjain2000** [comment]
We are rebuilding the website from scratch  , so this will not be a problem
