### ISSUE TITLE
Add a navigation header (Navbar)

### ISSUE THREAD

**Issue by 5tupidbrain** [CSwala/CSwala-website#21]
### Navigation Links (All links align to Left side except Signin)
- Logo (Redirect to index/home )
- Explore
- HackFeed
- JobHunt
- Signin (Right side)

### Navigation Design when User Logged in (All links align to Left side except 'plus icon' and 'username')
- Logo
- Explore
- HackFeed
- JobHunt
- Plus icon (Abbr - "Add new resource") (Right side)
- User icon with user name [Drop down menu] (Right side)

```
-------NOTE--------
- Dropdown menu [ 'edit profile', 'logout']
- Use dummy name and links for Logged-in navbar
```

**Comment by ashuvssut** [comment]
please assign me this issue
