### ISSUE TITLE
Add a Footer section!

### ISSUE THREAD

**Issue by 5tupidbrain** [CSwala/CSwala-website#22]
# Add a Footer section!

- **Footer has 2 Rows (Consist of Columns)**
- **Make it Responsive**
> Horizontal divider/border between rows

### First Row (Make headings bold)
- LOGO and name under logo `[1st Column]`
- Organization `[2st Column]:`
  - Home
  - About
  - FAQs
- Resources `[3st Column]:`
  - Projects
  - Docs
  - Learn More
- Let's chat `[4st Column]`
  - Email (cs.wala.guy@gmail.com)
  - Social icons in a single row (LinkedIn, Discord, GitHub)

### Second Row (all below should be in single line)
- Made with ❤ in 🇮🇳  `[Left align]`
- Copyright  2021 **CSWALA**, Org `[Center align]`
- Privacy Policy | Site Map | Report a bug `[Right align]`

**Comment by ashuvssut** [comment]
plz assign me this issue
