### ISSUE TITLE
Adding Explore Page 📚 [FrontEnd + API Request]

### ISSUE THREAD

**Issue by 5tupidbrain** [CSwala/CSwala-website#24]
# Add a Explore page

Take data from the CSwala API
> https://cswala-api.vercel.app/

save the object to "sessionStorage"

Create a display grid list, containing small cards which redirect to the detail page of that card.

### Card 
- Text {title,type} 
![Screenshot 2021-04-27 135311](https://user-images.githubusercontent.com/48384309/116209843-f0494f00-a75f-11eb-8893-6f7b4796d1c0.jpg)

### Responsive Grid
- use ` "container" ` class from bootstrap on explore page
- Grid Layout
  - below 990px (Grid: 2 columns)
  - default (Grid: 3 columns)
  - above 1400px (Grid: 4 columns)

**Comment by ashuvssut** [comment]
assign kr do mjhe

**Comment by Shivangi-ch** [comment]
If this is still open, can i work on it?
