### ISSUE TITLE
Adding Sign up page [FrontEnd]

### ISSUE THREAD

**Issue by AbhipsaGuru1012** [CSwala/CSwala-website#37]
Currently the website doesn't have a sign up page. I would like to add that.

**Comment by Saatvik21** [comment]
@5tupidbrain Can I work on this issue as it's been pending for more than 16 days?

**Comment by saranshhardaha** [comment]
@saatviknagpal ok

**Comment by iamtripathi25** [comment]
@5tupidbrain I would like to work on this.

**Comment by Rituresh143** [comment]
if this is pending please assign to me Gssoc22

**Comment by Aditya123987** [comment]
i want to work on this issue under Gssoc

**Comment by Nishita-2402** [comment]
Can I work on this issue ? I

**Comment by Ghanshyam89** [comment]
I want to work on this issue as there is no progress since 12 days.
Please assign this issue to me!!
