### ISSUE TITLE
Improvement in the teams section

### ISSUE THREAD

**Issue by Khushi-agarwal** [CSwala/CSwala-website#7]
I would like to update the font of meet our team and as well add hover effect on the card and on the icons of linked and GitHub.
So please @riturajjain2000 @ddvader44 @JayantGoel001 assign this issue to me so that I could work upon it.

**Comment by riturajjain2000** [comment]
Actually this Website is just a basic one , we are planning to have something that goes well with the theme of our app and can work like that as well , so no need for this issue as of now

If you are really interested in developing the website , I'll suggest you to Join our discord and discuss the implementation 

Closing this!
