### ISSUE TITLE
Update README file 

### ISSUE THREAD

**Issue by ANSHIKA1806** [CSwala/CSwala-website#8]
@riturajjain2000 @ddvader44 
README is the first file one should read when starting a new project. It's a set of useful information about a project, and a kind of manual. A README text file appears in many various places and refers not only to programming. So i want to make your README file more meaningful and more easier to understand the whole project.

**Comment by ANSHIKA1806** [comment]
@riturajjain2000 @ddvader44
Please assign this task to me uder Gssoc 2021. I would to contribute in your organization.
Thank you.

**Comment by riturajjain2000** [comment]
This is not under GSSOC

**Comment by ANSHIKA1806** [comment]
@riturajjain2000 
thanks for letting me know  sir .

**Comment by riturajjain2000** [comment]
Its added under GSSOC now
